//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<double> AdvanceRate { get; set; }
        public Nullable<double> MinimumInterest { get; set; }
        public Nullable<double> OriginationDiscount { get; set; }
        public Nullable<double> OriginationDiscount2 { get; set; }
        public Nullable<int> OriginationDiscountNumDays { get; set; }
        public Nullable<int> OriginationDiscountNumDays2 { get; set; }
        public Nullable<bool> InterestBasedOnAdvance { get; set; }
        public Nullable<bool> OriginationBasedOnAdvance { get; set; }
        public Nullable<bool> NoInterest { get; set; }
        public Nullable<double> ClientPrimeRate { get; set; }
        public Nullable<double> ClientPrimeRateSpread { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
