//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeeID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<double> MinimumInterest { get; set; }
        public Nullable<double> OriginationDiscount { get; set; }
        public Nullable<double> OriginationDiscount2 { get; set; }
        public Nullable<int> OriginationDiscountNumDays { get; set; }
        public Nullable<int> OriginationDiscountNumDays2 { get; set; }
        public Nullable<bool> InterestBasedOnAdvance { get; set; }
        public Nullable<bool> OriginationBasedOnAdvance { get; set; }
        public Nullable<bool> NoInterest { get; set; }
        public Nullable<double> InterestFee { get; set; }
        public Nullable<double> OriginationFee { get; set; }
        public Nullable<double> UnderwritingFee { get; set; }
        public Nullable<double> CustSvcUnderwritingDiscount { get; set; }
        public Nullable<double> CustSvcInterestDiscount { get; set; }
        public Nullable<double> CustSvcOriginationDiscount { get; set; }
        public Nullable<double> ClientPrimeRate { get; set; }
        public Nullable<double> ClientPrimeRateSpread { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
