//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funding
    {
        public int FundingID { get; set; }
        public int LoanID { get; set; }
        public Nullable<System.DateTime> DateDepositedInEscrow { get; set; }
        public Nullable<System.DateTime> BaileeLetterDate { get; set; }
        public Nullable<System.DateTime> InvestorProceedsDate { get; set; }
        public Nullable<double> InvestorProceeds { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
