//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LoanUW
    {
        public int LoanUWID { get; set; }
        public Nullable<int> LoanID { get; set; }
        [DisplayName("1003/1008 (Loan Application)")]
        public Nullable<bool> LoanUW10031008LoanApplication { get; set; }
        [DisplayName("Allonge Promissory Note")]
        public Nullable<bool> LoanUWAllongePromissoryNote { get; set; }
        [DisplayName("Appraisal")]
        public Nullable<bool> LoanUWAppraisal { get; set; }
        [DisplayName("Appraisal Amount")]
        public Nullable<double> LoanUWAppraisalAmount { get; set; }
        [DisplayName("Post Repair Appraisal Amount")]
        public Nullable<double> LoanUWPostRepairAppraisalAmount { get; set; }
        [DisplayName("Assignment of Mortgage")]
        public Nullable<bool> LoanUWAssignmentOfMortgage { get; set; }
        [DisplayName("Background Check")]
        public Nullable<bool> LoanUWBackgroundCheck { get; set; }
        [DisplayName("Certificate of Good Standing/Formation")]
        public Nullable<bool> LoanUWCertofGoodStandingFormation { get; set; }
        [DisplayName("Closing Protection Letter")]
        public Nullable<bool> LoanUWClosingProtectionLetter { get; set; }
        [DisplayName("Committee Review")]
        public Nullable<bool> LoanUWCommitteeReview { get; set; }
        [DisplayName("Credit Report")]
        public Nullable<bool> LoanUWCreditReport { get; set; }
        [DisplayName("Flood Certificate")]
        public Nullable<bool> LoanUWFloodCertificate { get; set; }
        [DisplayName("HUD-1 (Settlement Statement)")]
        public Nullable<bool> LoanUWHUD1SettlementStatement { get; set; }
        [DisplayName("Insurance (Homeowners)")]
        public Nullable<bool> LoanUWHomeownersInsurance { get; set; }
        [DisplayName("Loan Package (Closing Package and Instructions)")]
        public Nullable<bool> LoanUWLoanPackage { get; set; }
        [DisplayName("1003/1008 (Loan Application)")]
        public Nullable<bool> LoanUWLoanSizerLoanSubmissionTape { get; set; }
        [DisplayName("Title Commitment")]
        public Nullable<bool> LoanUWTitleCommitment { get; set; }
        [DisplayName("Loan Sizer /Approval")]
        public Nullable<bool> LoanUWClaytonReportApprovalEmail { get; set; }
        [DisplayName("Zillow Square Footage")]
        public Nullable<double> LoanUWZillowSqFt { get; set; }
        [DisplayName("Is Complete")]
        public Nullable<bool> LoanUWIsComplete { get; set; }
        [DisplayName("Completed By")]
        public Nullable<int> CompletedBy { get; set; }

        public virtual Loan Loan { get; set; }
    }
}
