//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.Fees = new HashSet<Fee>();
            this.Fundings = new HashSet<Funding>();
            this.LoanUWs = new HashSet<LoanUW>();
        }
    
        public int LoanID { get; set; }
        [DisplayName("Client")]
        public Nullable<int> LoanClientID { get; set; }
        [DisplayName("Entity")]
        public Nullable<int> LoanEntityID { get; set; }
        [DisplayName("Investor")]
        public Nullable<int> LoanInvestorID { get; set; }
        [DisplayName("Status")]
        public Nullable<int> LoanStatusID { get; set; }
        [DisplayName("Loan Number")]
        public string LoanNumber { get; set; }
        [DisplayFormat(DataFormatString = "{0: MM/dd/yyyy}")]
        [DisplayName("Closing/Funding Date")]
        public Nullable<System.DateTime> LoanFundingDate { get; set; }
        [DisplayName("Mortgagee")]
        public string LoanMortgagee { get; set; }
        [DisplayName("Property Address")]
        public string LoanPropertyAddress { get; set; }
        [DisplayName("Interest Rate")]
        [DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public Nullable<double> LoanInterestRate { get; set; }
        [DisplayName("Mortgage Amount")]
        public Nullable<double> LoanMortgageAmount { get; set; }
        [DisplayName("Advance Rate")]
        public Nullable<double> LoanAdvanceRate { get; set; }
        [DisplayName("Loan Type")]
        public Nullable<int> LoanTypeID { get; set; }
        public Nullable<System.DateTime> LoanEnteredDate { get; set; }
        public Nullable<System.DateTime> LoanUpdateDate { get; set; }
        public Nullable<int> LoanUpdateUserID { get; set; }
        [DisplayName("Business")]
        public string LoanMortgageeBusiness { get; set; }
        [DisplayName("Dwelling Type")]
        public Nullable<int> LoanDwellingType { get; set; }
        [DisplayName("State")]
        public Nullable<int> StateID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DwellingType DwellingType { get; set; }
        public virtual Entity Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funding> Fundings { get; set; }
        public virtual Investor Investor { get; set; }
        public virtual Status Status { get; set; }
        public virtual LoanType LoanType { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanUW> LoanUWs { get; set; }
    }
}
