//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAI_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAI_TestEntities5 : DbContext
    {
        public RAI_TestEntities5()
            : base("name=RAI_TestEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DwellingType> DwellingTypes { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<Funding> Fundings { get; set; }
        public virtual DbSet<Investor> Investors { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LoanUW> LoanUWs { get; set; }
        public virtual DbSet<vw_RAILoans> vw_RAILoans { get; set; }
    }
}
